# Generated by Django 5.0.1 on 2024-01-12 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='cat',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.cat'),
            preserve_default=False,
        ),
    ]
